/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Product {
  'id' : ProductId,
  'weight' : string,
  'inStock' : boolean,
  'originalPrice' : bigint,
  'subcategory' : string,
  'name' : string,
  'tags' : Array<string>,
  'discountLabel' : string,
  'imageUrl' : string,
  'discount' : bigint,
  'category' : string,
  'brand' : string,
  'rating' : number,
  'price' : bigint,
  'reviewCount' : bigint,
}
export type ProductId = bigint;
export interface _SERVICE {
  'getBestsellers' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];