/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'weight' : IDL.Text,
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Int,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'discountLabel' : IDL.Text,
  'imageUrl' : IDL.Text,
  'discount' : IDL.Int,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Int,
  'reviewCount' : IDL.Int,
});

export const idlService = IDL.Service({
  'getBestsellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'weight' : IDL.Text,
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Int,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'discountLabel' : IDL.Text,
    'imageUrl' : IDL.Text,
    'discount' : IDL.Int,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Int,
    'reviewCount' : IDL.Int,
  });
  
  return IDL.Service({
    'getBestsellers' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };